# Generated by Django 4.2.7 on 2026-09-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_auditlog_action_conceptprovenancelog'),
        ('patients', '0010_problemitem_cpoeorder_allergyitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(default='OUTBREAK_CLUSTER', max_length=40)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('cases_count', models.PositiveIntegerField(default=0)),
                ('threshold_breached', models.CharField(blank=True, max_length=255)),
                ('detected_date', models.DateField(auto_now_add=True)),
                ('alert_level', models.CharField(default='AMBER', max_length=20)),
                ('response_status', models.CharField(default='ACTIVE', max_length=30)),
                ('alert_sent_to_counties', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_health_events', to='core.facility')),
            ],
            options={
                'ordering': ['-detected_date', '-created_at'],
                'indexes': [models.Index(fields=['facility', 'alert_level'], name='surveillanc_facilit_2bd428_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotifiableDiseaseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disease_name', models.CharField(max_length=255)),
                ('icd_code', models.CharField(blank=True, default='', max_length=20)),
                ('urgency', models.CharField(default='HIGH', max_length=20)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('sub_county', models.CharField(blank=True, max_length=150)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='TRIGGERED', max_length=20)),
                ('moh_notified', models.BooleanField(default=False)),
                ('moh_notified_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_alerts', to='core.facility')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_alerts', to='patients.patient')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['facility', 'status'], name='surveillanc_facilit_7949c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdsrWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('epi_week', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('facility_mfl_code', models.CharField(blank=True, default='', max_length=30)),
                ('sub_county', models.CharField(blank=True, max_length=150)),
                ('county', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified')], default='DRAFT', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=150)),
                ('khis_submission_id', models.CharField(blank=True, default='', max_length=50)),
                ('diseases', models.JSONField(blank=True, default=list)),
                ('total_cases_summary', models.PositiveIntegerField(default=0)),
                ('total_deaths_summary', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idsr_weekly_reports', to='core.facility')),
            ],
            options={
                'ordering': ['-year', '-epi_week'],
                'indexes': [models.Index(fields=['facility', 'year', 'epi_week'], name='surveillanc_facilit_010ca8_idx')],
                'unique_together': {('facility', 'year', 'epi_week')},
            },
        ),
    ]
