# Generated by Django 4.2.7 on 2026-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_mpesatransaction_mpesaconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaconfig',
            name='transaction_type',
            field=models.CharField(choices=[('CustomerPayBillOnline', 'Paybill'), ('CustomerBuyGoodsOnline', 'Till Number')], default='CustomerPayBillOnline', max_length=50),
        ),
    ]
