# Generated by Django 4.2.7 on 2026-08-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_facility_subscription_package'),
        ('billing', '0004_alter_mpesaconfig_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='subscription_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='core.facilitysubscriptionpayment'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='billing.invoice'),
        ),
    ]
