# Generated by Django 4.2.7 on 2026-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_mpesatransaction_subscription_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaconfig',
            name='passkey',
            field=models.CharField(blank=True, default='bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919', max_length=255),
        ),
    ]
