# Generated by Django 4.2.7 on 2026-08-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_department_head_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('request_id', models.CharField(max_length=20)),
                ('patient', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=30)),
                ('ordered_by_employee_id', models.CharField(max_length=50)),
                ('ordered_by', models.CharField(max_length=150)),
                ('order_date', models.DateField()),
                ('sample_collected', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('STAT', 'STAT')], default='Routine', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='core.facility')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('test_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='core.facility')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lab_id', models.CharField(max_length=20)),
                ('parameters', models.JSONField(blank=True, default=list)),
                ('technician', models.CharField(max_length=150)),
                ('completed_date', models.DateField()),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('Awaiting Approval', 'Awaiting Approval'), ('Approved', 'Approved')], default='Awaiting Approval', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='core.facility')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.labrequest')),
            ],
            options={
                'ordering': ['-completed_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='labrequest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='laboratory.labtest'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['facility', 'test_id'], name='laboratory__facilit_93ee8d_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['facility', 'name'], name='laboratory__facilit_f1495b_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['facility', 'category'], name='laboratory__facilit_825b00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labtest',
            unique_together={('facility', 'test_id')},
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['facility', 'lab_id'], name='laboratory__facilit_cf5dae_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['facility', 'status'], name='laboratory__facilit_571c93_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['facility', 'completed_date'], name='laboratory__facilit_054c0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labresult',
            unique_together={('facility', 'lab_id')},
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['facility', 'request_id'], name='laboratory__facilit_bb3fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['facility', 'status'], name='laboratory__facilit_8db0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['facility', 'order_date'], name='laboratory__facilit_d9b264_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['facility', 'patient_id'], name='laboratory__facilit_3820c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labrequest',
            unique_together={('facility', 'request_id')},
        ),
    ]
