# Generated by Django 4.2.7 on 2026-08-27 07:47

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=core.models.default_permissions, help_text="JSON map of module keys to booleans. Valid keys: ['dashboard_overview', 'patients', 'appointments', 'visit_queue', 'ehr', 'pharmacy', 'laboratory', 'radiology', 'billing', 'inventory', 'reports', 'employees', 'departments', 'roles']")),
                ('is_system_role', models.BooleanField(default=False, help_text='True for auto-generated default roles; False for custom roles.')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.facility')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('facility', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.facilityrole'),
        ),
    ]
