# Generated by Django 4.2.7 on 2026-08-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rbac_facility_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='subscription_billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='subscription_package',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan'), ('enterprise', 'Enterprise Plan')], default='standard', max_length=50),
        ),
        migrations.CreateModel(
            name='FacilitySubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.CharField(max_length=50)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer')], default='mpesa', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='core.facility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
