# Generated by Django 4.2.7 on 2026-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_facility_subscription_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='subscription_package',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('professional', 'Professional Plan'), ('enterprise', 'Enterprise Plan')], default='professional', max_length=50),
        ),
    ]
