# Generated by Django 4.2.7 on 2026-09-15 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_facility_subscription_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('terminology_lookup', 'Terminology Lookup')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConceptProvenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.CharField(help_text='Coding system: KNHTS, ICD-10-WHO, SNOMED-CT, LOINC, etc.', max_length=50)),
                ('code', models.CharField(help_text='Concept code, e.g. I10, B54, J06.9', max_length=100)),
                ('display', models.CharField(blank=True, help_text='Human-readable concept label', max_length=500)),
                ('record_type', models.CharField(choices=[('ehr', 'EHR Record'), ('visit', 'Patient Visit'), ('lab', 'Lab Result'), ('radiology', 'Radiology Report')], max_length=20)),
                ('record_id', models.CharField(help_text='Primary key of the clinical record (EhrRecord.id or PatientVisit.id)', max_length=100)),
                ('looked_up_at', models.DateTimeField(help_text='Timestamp when the coded concept was applied to the clinical record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_provenance_logs', to='core.facility')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_provenance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concept Provenance Log',
                'verbose_name_plural': 'Concept Provenance Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', 'record_type', 'record_id'], name='core_concep_facilit_1fb19e_idx'), models.Index(fields=['facility', 'code_system', 'code'], name='core_concep_facilit_474b73_idx'), models.Index(fields=['facility', 'created_at'], name='core_concep_facilit_92eb74_idx')],
            },
        ),
    ]
