# Generated by Django 4.2.7 on 2026-08-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0003_patientvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EhrRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('doctor', models.CharField(max_length=150)),
                ('diagnosis', models.CharField(max_length=255)),
                ('symptoms', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='patientvisit',
            new_name='patients_pa_facilit_86c28a_idx',
            old_name='patients_pa_facilit_4f8db3_idx',
        ),
        migrations.RenameIndex(
            model_name='patientvisit',
            new_name='patients_pa_facilit_04300c_idx',
            old_name='patients_pa_facilit_0cb6e2_idx',
        ),
        migrations.AddField(
            model_name='ehrrecord',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehr_records', to='core.facility'),
        ),
        migrations.AddField(
            model_name='ehrrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehr_records', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='ehrrecord',
            index=models.Index(fields=['facility', 'patient', 'date'], name='patients_eh_facilit_55c0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='ehrrecord',
            index=models.Index(fields=['facility', 'date'], name='patients_eh_facilit_27bd32_idx'),
        ),
    ]
