# Generated by Django 4.2.7 on 2026-08-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_ehr_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='prescriptions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
