# Generated by Django 4.2.7 on 2026-08-25 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_emailotp'),
        ('patients', '0006_patientvisit_prescription_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutpatientTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ticket_number', models.CharField(max_length=30)),
                ('destination', models.CharField(choices=[('reception', 'Reception'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing')], default='consultation', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_outpatient_tickets', to=settings.AUTH_USER_MODEL)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_outpatient_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outpatient_tickets', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_tickets', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpatient_tickets', to='patients.patient')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutpatientTicketMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_destination', models.CharField(blank=True, choices=[('reception', 'Reception'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing')], max_length=20)),
                ('to_destination', models.CharField(choices=[('reception', 'Reception'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL)),
                ('forwarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_forwards', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='patients.outpatientticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='outpatientticket',
            index=models.Index(fields=['facility', 'destination', 'status', 'created_at'], name='patients_ou_facilit_d4b6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='outpatientticket',
            index=models.Index(fields=['facility', 'patient', 'status'], name='patients_ou_facilit_0012d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outpatientticket',
            unique_together={('facility', 'ticket_number')},
        ),
    ]
