# Generated by Django 4.2.7 on 2026-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_outpatientticket_outpatientticketmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='national_id_or_birth_certificate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['facility', 'national_id_or_birth_certificate'], name='patients_pa_facilit_6459c8_idx'),
        ),
    ]
