# Generated by Django 4.2.7 on 2026-09-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_auditlog_action_conceptprovenancelog'),
        ('patients', '0009_knhts_diagnosis_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('system', models.CharField(blank=True, default='KNHTS', max_length=50)),
                ('display', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=150)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_items', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_items', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', 'patient'], name='patients_pr_facilit_3ec8fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='CpoeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('system', models.CharField(blank=True, default='', max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('ordered_by', models.CharField(blank=True, max_length=150)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('billing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpoe_orders', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpoe_orders', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', 'patient'], name='patients_cp_facilit_ae8cb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AllergyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allergen_name', models.CharField(max_length=255)),
                ('allergen_code', models.CharField(blank=True, default='', max_length=50)),
                ('allergy_type', models.CharField(default='Medication', max_length=30)),
                ('severity', models.CharField(default='Moderate', max_length=20)),
                ('reaction', models.CharField(blank=True, max_length=255)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_items', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_items', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', 'patient'], name='patients_al_facilit_2ac9f9_idx')],
            },
        ),
    ]
