# Generated by Django 4.2.7 on 2026-08-04 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('drug_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='core.facility')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', 'drug_id'], name='pharmacy_dr_facilit_a0b690_idx'), models.Index(fields=['facility', 'name'], name='pharmacy_dr_facilit_bee63f_idx'), models.Index(fields=['facility', 'category'], name='pharmacy_dr_facilit_a2d45f_idx'), models.Index(fields=['facility', 'is_active'], name='pharmacy_dr_facilit_f9f5c3_idx')],
                'unique_together': {('facility', 'drug_id')},
            },
        ),
    ]
