# Generated by Django 4.2.7 on 2026-08-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prescription_id', models.CharField(max_length=20)),
                ('patient_id', models.CharField(max_length=30)),
                ('doctor_id', models.CharField(max_length=30)),
                ('drugs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dispensed', 'Dispensed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('date', models.DateField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.facility')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['facility', 'prescription_id'], name='pharmacy_pr_facilit_be333b_idx'), models.Index(fields=['facility', 'status'], name='pharmacy_pr_facilit_fa49cc_idx'), models.Index(fields=['facility', 'date'], name='pharmacy_pr_facilit_074884_idx'), models.Index(fields=['facility', 'patient_id'], name='pharmacy_pr_facilit_4c9d44_idx')],
                'unique_together': {('facility', 'prescription_id')},
            },
        ),
    ]
