# Generated by Django 4.2.7 on 2026-09-11 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_facility_subscription_package'),
        ('pharmacy', '0002_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_categories', to='core.facility')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='pharmacy.drugcategory'),
        ),
        migrations.AddIndex(
            model_name='drugcategory',
            index=models.Index(fields=['facility', 'name'], name='pharmacy_dr_facilit_f2d66b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='drugcategory',
            unique_together={('facility', 'name')},
        ),
    ]
