# Generated by Django 4.2.7 on 2026-09-11 07:10

from django.db import migrations
import json

STANDARD_CATEGORIES = [
    {
      "category": "Analgesics",
      "description": "Pain relievers",
      "examples": ["Paracetamol", "Ibuprofen", "Morphine"]
    },
    {
      "category": "Antibiotics",
      "description": "Treat bacterial infections",
      "examples": ["Amoxicillin", "Azithromycin", "Ciprofloxacin"]
    },
    {
      "category": "Antivirals",
      "description": "Treat viral infections",
      "examples": ["Acyclovir", "Valacyclovir", "Remdesivir"]
    },
    {
      "category": "Antifungals",
      "description": "Treat fungal infections",
      "examples": ["Fluconazole", "Clotrimazole", "Ketoconazole"]
    },
    {
      "category": "Antihypertensives",
      "description": "Lower high blood pressure",
      "examples": ["Lisinopril", "Amlodipine", "Losartan"]
    },
    {
      "category": "Antidiabetics",
      "description": "Manage blood sugar levels",
      "examples": ["Metformin", "Insulin", "Glipizide"]
    },
    {
      "category": "Antidepressants",
      "description": "Treat depression and mood disorders",
      "examples": ["Sertraline", "Fluoxetine", "Citalopram"]
    },
    {
      "category": "Antihistamines",
      "description": "Relieve allergy symptoms",
      "examples": ["Cetirizine", "Loratadine", "Diphenhydramine"]
    },
    {
      "category": "Statins",
      "description": "Lower cholesterol levels",
      "examples": ["Atorvastatin", "Simvastatin", "Rosuvastatin"]
    },
    {
      "category": "Bronchodilators",
      "description": "Open airways for respiratory conditions",
      "examples": ["Albuterol", "Salmeterol", "Formoterol"]
    }
]

def migrate_categories(apps, schema_editor):
    Drug = apps.get_model('pharmacy', 'Drug')
    DrugCategory = apps.get_model('pharmacy', 'DrugCategory')
    Facility = apps.get_model('core', 'Facility')

    # Seed standard categories for all existing facilities
    facilities = Facility.objects.all()
    for facility in facilities:
        for cat in STANDARD_CATEGORIES:
            DrugCategory.objects.get_or_create(
                facility=facility,
                name=cat['category'],
                defaults={'description': cat['description']}
            )

    # Migrate existing categories on drugs
    for drug in Drug.objects.all():
        if drug.category:
            cat_name = drug.category.strip()
            if cat_name:
                category_obj, _ = DrugCategory.objects.get_or_create(
                    facility=drug.facility,
                    name=cat_name
                )
                drug.category_fk = category_obj
                drug.save(update_fields=['category_fk'])

def reverse_migrate_categories(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_drugcategory_drug_category_fk_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_categories, reverse_migrate_categories),
    ]
