# Generated by Django 4.2.7 on 2026-09-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_migrate_drug_categories'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drug',
            name='pharmacy_dr_facilit_a2d45f_idx',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='category',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['facility', 'category'], name='pharmacy_dr_facilit_8daab7_idx'),
        ),
    ]
