# Generated by Django 4.2.7 on 2026-10-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_drug_terminology_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='drug',
            new_name='pharmacy_dr_facilit_a03a6d_idx',
            old_name='pharmacy_dr_facilit_0c279b_idx',
        ),
    ]
