# Generated by Django 4.2.7 on 2026-08-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(choices=[('general', 'General Overview'), ('patients', 'Patient Growth Report'), ('pharmacy', 'Pharmacy Performance'), ('inventory', 'Inventory Status'), ('laboratory', 'Laboratory Activity'), ('employees', 'Employee Analytics'), ('revenue', 'Revenue & Finance')], default='general', max_length=50)),
                ('time_range', models.CharField(default='30days', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('chart_type', models.CharField(choices=[('line', 'Line Chart'), ('bar', 'Bar Chart')], default='line', max_length=20)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of roles authorized to view this report')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='core.facility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
