# Generated by Django 4.2.7 on 2026-10-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_auditlog_action_conceptprovenancelog'),
        ('patients', '0010_problemitem_cpoeorder_allergyitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAIConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('chief_complaint', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('vitals_snapshot', models.JSONField(blank=True, default=dict)),
                ('labs_snapshot', models.JSONField(blank=True, default=list)),
                ('imaging_snapshot', models.JSONField(blank=True, default=list)),
                ('clinical_summary', models.TextField(blank=True)),
                ('model_version', models.CharField(default='v1.0.0', max_length=100)),
                ('knowledge_version', models.CharField(default='v1.0.0', max_length=100)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_consultations', to='patients.ehrrecord')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_consultations', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_consultations', to='patients.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_ai_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAIModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Afyora Clinical CDS', max_length=100)),
                ('version', models.CharField(default='v1.0.0', max_length=50)),
                ('prompt_version', models.CharField(default='p1.0.0', max_length=50)),
                ('clinical_rules_version', models.CharField(default='r1.0.0', max_length=50)),
                ('medication_db_version', models.CharField(default='m1.0.0', max_length=50)),
                ('guideline_version', models.CharField(default='g1.0.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recommendation_type', models.CharField(choices=[('differential_diagnosis', 'Differential Diagnosis'), ('treatment_recommendation', 'Treatment Recommendation'), ('investigation', 'Recommended Investigation'), ('safety_alert', 'Medication Safety Alert'), ('red_flag', 'Red Flag Emergency Alert'), ('lifestyle', 'Diet & Lifestyle Guidance'), ('patient_education', 'Patient Education'), ('follow_up', 'Follow-up Recommendation')], max_length=40)),
                ('recommendation', models.JSONField(default=dict)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('clinician_action', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='pending', max_length=20)),
                ('clinician_modified_value', models.JSONField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='clinical_ai.clinicalaiconsultation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified')], max_length=20)),
                ('feedback_text', models.TextField(blank=True)),
                ('modified_value', models.JSONField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_payload', models.JSONField(blank=True, null=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_ai_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='clinical_ai.clinicalaiconsultation')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_ai_feedbacks', to='core.facility')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='clinical_ai.clinicalairecommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAIAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_ref', models.CharField(help_text='Pseudonymized or ID reference', max_length=100)),
                ('consultation_ref', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('consultation_requested', 'Consultation Requested'), ('context_accessed', 'Patient Context Accessed'), ('response_generated', 'AI Response Generated'), ('recommendation_accepted', 'Recommendation Accepted'), ('recommendation_rejected', 'Recommendation Rejected'), ('recommendation_modified', 'Recommendation Modified'), ('prescription_finalized', 'Prescription Finalized'), ('feedback_submitted', 'Feedback Submitted'), ('security_violation', 'Security Violation'), ('service_fallback', 'Service Fallback Triggered')], max_length=40)),
                ('action_details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audit_events', to='core.facility')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalairecommendation',
            index=models.Index(fields=['consultation', 'recommendation_type'], name='clinical_ai_consult_173fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalairecommendation',
            index=models.Index(fields=['consultation', 'clinician_action'], name='clinical_ai_consult_c69303_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalaifeedback',
            index=models.Index(fields=['facility', 'action'], name='clinical_ai_facilit_2d76bc_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalaifeedback',
            index=models.Index(fields=['clinician', 'created_at'], name='clinical_ai_clinici_eed4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalaiconsultation',
            index=models.Index(fields=['facility', 'patient'], name='clinical_ai_facilit_b64cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalaiconsultation',
            index=models.Index(fields=['facility', 'requested_by'], name='clinical_ai_facilit_bbbef9_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalaiconsultation',
            index=models.Index(fields=['facility', 'status'], name='clinical_ai_facilit_f5e304_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalaiauditevent',
            index=models.Index(fields=['facility', 'created_at'], name='clinical_ai_facilit_0bfe72_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalaiauditevent',
            index=models.Index(fields=['facility', 'event_type'], name='clinical_ai_facilit_888485_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalaiauditevent',
            index=models.Index(fields=['user', 'event_type'], name='clinical_ai_user_id_ea808e_idx'),
        ),
    ]
