# Generated by Django 4.2.7 on 2026-09-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminologyCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(choices=[('SNOMED-CT', 'SNOMED CT'), ('ICD-11', 'ICD-11'), ('LOINC', 'LOINC'), ('KNHTS', 'KNHTS'), ('CIEL', 'CIEL'), ('KEMSA-HPT', 'KEMSA HPT')], max_length=50, unique=True)),
                ('version', models.CharField(default='2024', max_length=50)),
                ('total_concepts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Updating', 'Updating'), ('Error', 'Error'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Terminology Catalog',
            },
        ),
        migrations.CreateModel(
            name='MedicationHPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kemsa_code', models.CharField(help_text='KEMSA/KNHTS drug code', max_length=50, unique=True)),
                ('generic_name', models.CharField(max_length=255)),
                ('brand_names', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('Essential Medicine', 'Essential Medicine'), ('Antiretroviral', 'Antiretroviral'), ('Vaccine', 'Vaccine'), ('Diagnostic', 'Diagnostic'), ('Medical Supply', 'Medical Supply'), ('Equipment', 'Equipment')], default='Essential Medicine', max_length=50)),
                ('dosage_form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Suppository', 'Suppository'), ('Powder', 'Powder'), ('Suspension', 'Suspension'), ('Other', 'Other')], default='Tablet', max_length=50)),
                ('strength', models.CharField(blank=True, help_text='e.g., 500mg, 250mg/5ml', max_length=100, null=True)),
                ('route_of_administration', models.CharField(blank=True, max_length=100, null=True)),
                ('knhts_code', models.CharField(blank=True, max_length=50, null=True)),
                ('snomed_code', models.CharField(blank=True, max_length=50, null=True)),
                ('atc_code', models.CharField(blank=True, help_text='WHO ATC Classification code', max_length=50, null=True)),
                ('is_on_essential_medicines_list', models.BooleanField(default=True)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medication / HPT Registry Entry',
                'ordering': ['generic_name'],
                'indexes': [models.Index(fields=['generic_name'], name='knhts_medic_generic_e0a4ed_idx'), models.Index(fields=['kemsa_code'], name='knhts_medic_kemsa_c_7744ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='KNHTSConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('code_system', models.CharField(choices=[('SNOMED-CT', 'SNOMED CT'), ('ICD-11', 'ICD-11'), ('LOINC', 'LOINC'), ('KNHTS', 'KNHTS'), ('CIEL', 'CIEL'), ('KEMSA-HPT', 'KEMSA Health Products & Technologies'), ('HL7-FHIR', 'HL7 FHIR')], default='KNHTS', max_length=50)),
                ('display', models.CharField(max_length=500)),
                ('domain', models.CharField(choices=[('Diagnosis', 'Diagnosis'), ('Procedure', 'Procedure'), ('Medication', 'Medication'), ('Laboratory', 'Laboratory'), ('Observation', 'Observation'), ('Gender', 'Gender'), ('Finding', 'Finding'), ('Anatomy', 'Anatomy')], default='Diagnosis', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, help_text='Comma-separated synonym terms', null=True)),
                ('parent_code', models.CharField(blank=True, help_text='Parent concept code', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KNHTS Concept',
                'ordering': ['code_system', 'code'],
                'indexes': [models.Index(fields=['code_system', 'domain'], name='knhts_knhts_code_sy_a284ec_idx'), models.Index(fields=['display'], name='knhts_knhts_display_a52eb2_idx')],
            },
        ),
    ]
