# Generated by Django 4.2.7 on 2026-08-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('study_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_studies', to='core.facility')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImagingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('request_id', models.CharField(max_length=20)),
                ('patient', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=30)),
                ('ordered_by_employee_id', models.CharField(max_length=50)),
                ('ordered_by', models.CharField(max_length=150)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('STAT', 'STAT')], default='Routine', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_requests', to='core.facility')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='radiology.imagingstudy')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['facility', 'study_id'], name='radiology_i_facilit_84d0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['facility', 'name'], name='radiology_i_facilit_0fa7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['facility', 'category'], name='radiology_i_facilit_08ed17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagingstudy',
            unique_together={('facility', 'study_id')},
        ),
        migrations.AddIndex(
            model_name='imagingrequest',
            index=models.Index(fields=['facility', 'request_id'], name='radiology_i_facilit_96dd12_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingrequest',
            index=models.Index(fields=['facility', 'status'], name='radiology_i_facilit_da76f5_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingrequest',
            index=models.Index(fields=['facility', 'order_date'], name='radiology_i_facilit_0ce654_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingrequest',
            index=models.Index(fields=['facility', 'patient_id'], name='radiology_i_facilit_f57aef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagingrequest',
            unique_together={('facility', 'request_id')},
        ),
    ]
