# Generated by Django 4.2.7 on 2026-08-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailotp'),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_id', models.CharField(max_length=20)),
                ('radiologist', models.CharField(max_length=150)),
                ('scan_date', models.DateField()),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Finalized', 'Finalized')], default='Draft', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_reports', to='core.facility')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='radiology.imagingrequest')),
            ],
            options={
                'ordering': ['-scan_date', '-created_at'],
                'indexes': [models.Index(fields=['facility', 'report_id'], name='radiology_i_facilit_52dec6_idx'), models.Index(fields=['facility', 'status'], name='radiology_i_facilit_0c9f75_idx')],
                'unique_together': {('facility', 'report_id')},
            },
        ),
    ]
