# Generated by Django 4.2.7 on 2026-08-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_imagingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingstudy',
            name='body_part',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='modality',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
