# Generated by Django 4.2.7 on 2026-08-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailotp'),
        ('radiology', '0003_imagingstudy_body_part_imagingstudy_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('source', models.CharField(default='uploaded', max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_images', to='core.facility')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='radiology.imagingrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', 'request'], name='radiology_i_facilit_aeeb87_idx')],
            },
        ),
    ]
