# Generated by Django 4.2.7 on 2026-07-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_e_facilit_169631_idx',
            old_name='employees_e_facilit_f95be2_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_e_facilit_cdfbeb_idx',
            old_name='employees_e_facilit_a8ce11_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_e_facilit_b24c89_idx',
            old_name='employees_e_facilit_bf768a_idx',
        ),
    ]
