# Generated by Django 4.2.7 on 2026-08-27 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rbac_facility_roles'),
        ('employees', '0002_rename_employees_e_facilit_f95be2_idx_employees_e_facilit_169631_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.facilityrole'),
        ),
    ]
