# Generated by Django 4.2.7 on 2026-09-05 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_facility_subscription_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0003_rbac_facility_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('clocked_in', 'Clocked In'), ('clocked_out', 'Clocked Out'), ('late', 'Late'), ('absent', 'Absent')], default='clocked_in', max_length=20)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='core.facility')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-clock_in'],
                'indexes': [models.Index(fields=['facility', 'date'], name='employees_e_facilit_8bb4ae_idx'), models.Index(fields=['employee', 'date'], name='employees_e_employe_fe9776_idx'), models.Index(fields=['status'], name='employees_e_status_55d377_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
