# Generated by Django 4.2.7 on 2026-07-24 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_age'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointment_id', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctor', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['date', 'time', '-created_at'],
                'indexes': [models.Index(fields=['facility', 'appointment_id'], name='appointment_facilit_bea1cb_idx'), models.Index(fields=['facility', 'date'], name='appointment_facilit_2d9b67_idx'), models.Index(fields=['facility', 'status'], name='appointment_facilit_b77cb4_idx'), models.Index(fields=['facility', 'patient'], name='appointment_facilit_a90d9d_idx')],
                'unique_together': {('facility', 'appointment_id')},
            },
        ),
    ]
