# Generated by Django 4.2.7 on 2026-09-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_auditlog_action_conceptprovenancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HieConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('endpoint', models.URLField(default='https://hie.health.go.ke/api/v1/fhir')),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('TESTING', 'Testing'), ('ERROR', 'Error')], default='DISCONNECTED', max_length=20)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('maturity_level', models.PositiveSmallIntegerField(default=1)),
                ('mfl_code', models.CharField(blank=True, default='', max_length=30)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hie_connection', to='core.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TerminologyStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, default='', max_length=100)),
                ('active_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SYNCED', 'Synced'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminology_standards', to='core.facility')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('facility', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QualityMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Maternal & Child Health', 'Maternal & Child Health'), ('Communicable Diseases', 'Communicable Diseases'), ('Non-Communicable Diseases', 'Non-Communicable Diseases'), ('Hospital Operational', 'Hospital Operational')], default='Hospital Operational', max_length=40)),
                ('numerator_description', models.CharField(blank=True, max_length=255)),
                ('denominator_description', models.CharField(blank=True, max_length=255)),
                ('numerator_value', models.PositiveIntegerField(default=0)),
                ('denominator_value', models.PositiveIntegerField(default=0)),
                ('target_rate', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('last_calculated', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_measures', to='core.facility')),
            ],
            options={
                'ordering': ['category', 'code'],
                'unique_together': {('facility', 'code')},
            },
        ),
        migrations.CreateModel(
            name='HieSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('log_type', models.CharField(choices=[('OUTBOUND_BUNDLE', 'Outbound FHIR Bundle'), ('SURVEILLANCE_SDMX', 'Surveillance SDMX Export'), ('QUALITY_MEASURE', 'Quality Measure Submission'), ('PATIENT_PUSH', 'Patient Push')], max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('QUEUED', 'Queued')], default='SUCCESS', max_length=20)),
                ('records_transferred', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('payload_snippet', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hie_sync_logs', to='core.facility')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', 'log_type'], name='interoperab_facilit_8b646b_idx')],
            },
        ),
    ]
